### ISSUE TITLE
Bottom Left Rotary Conflict with Adverse Yaw Setting?

### ISSUE THREAD

**Issue by pvaiko** [JackBilbo/lxn-discus#17]
I'm probably missing something, but the 2.0.5.1 (latest) Discus 2c premium has the bottom left rotary button assigned to set the adverse yaw %. When I have the lxn-discus installed, hovering over that button shows XXXX 50% (without lxn-discus it is ADVERSE YAW xx%). When turning the button, it changes to the next page but wondering if it changes the adverse yaw setting? The % value for the adverse yaw momentarily changes to 60% when rotating in one direction, and to 40% when rotating in the other, but then it always returns to 50%. 

![image](https://user-images.githubusercontent.com/2379521/212550308-8a57ebd1-2b67-47fc-a22f-bdcd7d156396.png)

**Comment by JackBilbo** [comment]
Yep. That adverse yaw setting was introduced right after i started using the rotary buttons for page switching. As an alternative i built a slider in the aircraft settings where you can adjust the setting. The value you set there should also be persistent between flightsim sessions. Just check out the config page / aircraft settings.

**Comment by pvaiko** [comment]
Oh, I see, I downloaded it from flightsim.to, that version does not seem to have the adverse yaw slider. Will use the latest from here, thanks.
