### ISSUE TITLE
New Variable required - WPT Delta Height to Min

### ISSUE THREAD

**Issue by poundy** [JackBilbo/lxn-discus#9]
The one variable the .6 release needs, to be able to be put on the data point grid in the WPT map page, is the current estimated WPT Delta height. 
On the task WPT list you use the red colour to show when: Arrivalheight msl < min.height || est. Arrivalheight msl > max.height (plus below ground level) and what would be great to have (and what Ian has on the AS33) is the delta to min.height. So a calculated value of (ArrivalHeightMSL - min.height) will tell you how much height you need, if negative, or how much extra you have, if positive, to fly faster with, at a glance. Yes, I can roughly do the maths in my head but that's more taxing on a long flight than needs to be.

**Comment by JackBilbo** [comment]
No problem to put that in. The only issue i see is, that at least 90% of waypoints don't have a min-value. There the reading would be identical with arrival height above ground level/waypoint altitude. Might as well just add min-height to wp-altitude and change the label from "WP ARR (AGL)" to "WP ARR (WP-ALT)".

**Comment by poundy** [comment]
I'd contend that 90% of WPs I use (at the moment) DO stipulate a minimum alt, but that's because at the moment I tend to be trying more "competition" style courses prepared by others. I don't mind your approach but I do think the AGL value also has merit - I'd still propose creating an extra variable?

**Comment by JackBilbo** [comment]
Convinced. I'm propably not racing enough :-) Will be in for the weekend.
